'use client';

export const LABELS: Record<string, string> = {
  site_name: 'Site Name',
  site_short_name: 'Short Name',
  site_tagline: 'Tagline',
  site_description: 'Site Description',
  seo_title: 'Meta Title',
  seo_description: 'Meta Description',
  hero_tagline: 'Hero Tagline',
  hero_headline: 'Hero Headline',
  hero_slides: 'Hero Slider Images',
  video_url: 'Our Story Video URL',
  footer_about: 'Footer About Text',
  newsletter_text: 'Newsletter Blurb',
  newsletter_title: 'Newsletter Title',
  header_help_label: 'Header "Get Help" Label',
  header_support_label: 'Header "Support Us" Label',
  org_legal_name: 'Legal / Full Name',
  org_logo: 'Organisation Logo',
  org_registration_number: 'Registration Number',
  org_founded_year: 'Founded Year',
  org_website: 'Official Website',
  org_motto: 'Motto',
  contact_email: 'Email',
  contact_phone: 'Phone (Display)',
  contact_phone_raw: 'Phone (Raw / International)',
  contact_address: 'Address',
  contact_whatsapp: 'WhatsApp Number',
  contact_map_query: 'Map Query',
  contact_info_title: 'Info Section Title',
  contact_info_description: 'Info Section Description',
  contact_cta_title: 'CTA Title',
  contact_cta_description: 'CTA Description',
  contact_follow_title: 'Follow Us Title',
  contact_office_hours: 'Office Hours',
  contact_faqs: 'FAQs',
  support_whatsapp: 'Support WhatsApp',
  support_phone: 'Support Phone',
  support_email: 'Support Email',
  support_heading: 'Support Heading',
  support_description: 'Support Description',
  support_status_label: 'Status Label',
  support_chat_label: 'Chat Button Label',
  support_chat_channel: 'Chat Channel',
  support_call_label: 'Call Button Label',
  support_email_label: 'Email Button Label',
  support_crisis_text: 'Crisis Text',
  social_facebook: 'Facebook URL',
  social_twitter: 'Twitter / X URL',
  social_instagram: 'Instagram URL',
  social_linkedin: 'LinkedIn URL',
  social_youtube: 'YouTube URL',
  stat_people_supported: 'People Supported',
  stat_community_events: 'Community Events',
  stat_volunteers: 'Volunteers',
  stat_commitment: 'Commitment (%)',
  donation_bank_name: 'Bank Name',
  donation_account_number: 'Account Number',
  donation_account_name: 'Account Name',
  donation_sort_code: 'Sort Code',
  about_values: 'Values',
  about_areas: 'Areas of Intervention',
  about_milestones: 'Milestones',
  about_values_label: 'Values Section Label',
  about_values_title: 'Values Title',
  about_values_description: 'Values Description',
  about_areas_eyebrow: 'Areas Eyebrow',
  about_areas_title: 'Areas Title',
  about_areas_description: 'Areas Description',
  about_journey_eyebrow: 'Journey Eyebrow',
  about_journey_title: 'Journey Title',
  about_who_title: 'Who We Are Title',
  about_who_paragraphs: 'Who We Are Paragraphs',
  about_mission_more: 'Mission (extended)',
  about_vision_more: 'Vision (extended)',
  about_years_label: 'Years of Impact Label',
  about_story_cta: 'Story CTA Label',
  about_mission_label: 'Mission Label',
  about_vision_label: 'Vision Label',
  about_mission: 'Homepage Mission',
  about_vision: 'Homepage Vision',
  about_eyebrow: 'Homepage About Eyebrow',
  about_title: 'Homepage About Title',
  about_description: 'Homepage About Description',
  about_hero_eyebrow: 'Hero Eyebrow',
  about_hero_title: 'Hero Title',
  about_hero_title_highlight: 'Hero Title Highlight',
  about_hero_description: 'Hero Description',
  about_team_title: 'Team Section Title',
  about_team_eyebrow: 'Team Section Eyebrow',
  about_cta_title: 'Bottom CTA Title',
  about_cta_description: 'Bottom CTA Description',
  founders_eyebrow: 'Founders Eyebrow',
  founders_title: 'Founders Title',
  founders_description: 'Founders Description',
  motto_eyebrow: 'Motto Eyebrow',
  motto_part1: 'Motto Part 1',
  motto_part2: 'Motto Part 2',
  motto_part3: 'Motto Part 3',
  motto_sub: 'Motto Subtext',
  help_helplines: 'Helplines',
  help_channels: 'Contact Channels',
  help_warning_signs: 'Warning Signs',
  help_self_care_steps: 'Self-Care Steps',
  help_helplines_title: 'Helplines Title',
  help_channels_title: 'Channels Title',
  help_warning_title: 'Warning Signs Title',
  help_warning_description: 'Warning Signs Description',
  help_crisis_title: 'Crisis Title',
  help_crisis_description: 'Crisis Description',
  help_steps_eyebrow: 'Steps Eyebrow',
  help_steps_title: 'Steps Title',
  help_steps_description: 'Steps Description',
  help_resources_title: 'Resources Title',
  help_cta_title: 'CTA Title',
  help_cta_description: 'CTA Description',
  help_hero_eyebrow: 'Hero Eyebrow',
  help_hero_title: 'Hero Title',
  help_hero_title_highlight: 'Hero Title Highlight',
  help_hero_description: 'Hero Description',
  involve_ways: 'Ways to Get Involved',
  involve_steps: 'Getting Started Steps',
  involve_hero_eyebrow: 'Hero Eyebrow',
  involve_hero_title: 'Hero Title',
  involve_hero_title_highlight: 'Hero Title Highlight',
  involve_hero_description: 'Hero Description',
  involve_ways_title: 'Ways Title',
  involve_how_title: 'How Title',
  involve_how_description: 'How Description',
  involve_contact_title: 'Contact Title',
  involve_cta_title: 'CTA Title',
  involve_cta_description: 'CTA Description',
  involve_stat_people_label: 'Stat: People Label',
  involve_stat_volunteers_label: 'Stat: Volunteers Label',
  involve_stat_events_label: 'Stat: Events Label',
  involve_stat_free_label: 'Stat: Free Label',
  services_list: 'Services List',
  features_list: 'Features List',
  partners_list: 'Partners List',
  resources_page_eyebrow: 'Resources Page Eyebrow',
  resources_page_title: 'Resources Page Title',
  resources_page_title_highlight: 'Resources Page Title Highlight',
  resources_page_description: 'Resources Page Description',
  partners_page_eyebrow: 'Partners Page Eyebrow',
  partners_page_title: 'Partners Page Title',
  partners_page_title_highlight: 'Partners Page Title Highlight',
  partners_page_description: 'Partners Page Description',
  registration_interests: 'Registration Interests',
  projects_categories: 'Project Categories',
  gallery_categories: 'Gallery Categories',
  insights_trending_tags: 'Trending Tags',
  impact_stats: 'Impact Stats',
  wwd_hero_image: 'What We Do Hero Image',
  wwd_hero_eyebrow: 'Hero Eyebrow',
  wwd_hero_title: 'Hero Title',
  wwd_hero_title_highlight: 'Hero Title Highlight',
  wwd_hero_description: 'Hero Description',
  wwd_section_eyebrow: 'Services Section Eyebrow',
  wwd_section_title: 'Services Section Title',
  wwd_section_description: 'Services Section Description',
  wwd_steps_title: 'Steps Title',
  wwd_steps_title_highlight: 'Steps Title Highlight',
  wwd_steps: 'How It Works Steps',
  wwd_steps_eyebrow: 'Steps Eyebrow',
  wwd_card_explore_label: 'Service Card "Explore" Label',
  wwd_cta_title: 'Bottom CTA Title',
  wwd_cta_description: 'Bottom CTA Description',
  wwd_cta_help_label: 'Bottom CTA "Get Help" Label',
  wwd_cta_contact_label: 'Bottom CTA "Contact" Label',
  wwd_meta_title: 'What We Do — Meta Title',
  wwd_meta_description: 'What We Do — Meta Description',
  services_bg_image: 'Services Section Background Image',
  services_eyebrow: 'Homepage Services Eyebrow',
  services_title: 'Homepage Services Title',
  services_title_highlight: 'Homepage Services Title Highlight',
  services_description: 'Homepage Services Description',
  services_explore_cta: 'Explore All Services Label',
  services_help_cta: 'Get Help Label',
  sp_back_label: 'Service Page "Back" Label',
  sp_why_eyebrow: 'Service Page "Why It Matters" Eyebrow',
  sp_activities_eyebrow: 'Service Page Activities Eyebrow',
  sp_activities_title: 'Service Page Activities Title',
  sp_impact_eyebrow: 'Service Page Impact Eyebrow',
  sp_impact_title: 'Service Page Impact Title',
  sp_cta_primary: 'Service Page Primary CTA Label',
  sp_cta_secondary: 'Service Page Secondary CTA Label',
  service_page_awareness: 'Service Page — Mental Health Awareness',
  service_page_education: 'Service Page — Mental Health Education',
  service_page_referral: 'Service Page — Professional Referral',
  service_page_community: 'Service Page — Community Support',
  service_page_vulnerable: 'Service Page — Vulnerable Persons',
  service_page_research: 'Service Page — Research & Advocacy',
  projects_hero_eyebrow: 'Hero Eyebrow',
  projects_hero_title: 'Hero Title',
  projects_hero_title_highlight: 'Hero Title Highlight',
  projects_hero_description: 'Hero Description',
  projects_cta_title: 'CTA Title',
  projects_cta_description: 'CTA Description',
  projects_view_all_cta: 'View All Projects Label',
  projects_donate_cta: 'Donate Now Label',
  projects_stat_lives: 'Stat: Lives Impacted',
  projects_stat_active: 'Stat: Active Projects',
  projects_stat_communities: 'Stat: Communities',
  projects_stat_funds: 'Stat: Funds Raised',
  events_hero_eyebrow: 'Hero Eyebrow',
  events_hero_title: 'Hero Title',
  events_hero_title_highlight: 'Hero Title Highlight',
  events_hero_description: 'Hero Description',
  events_upcoming_title: 'Upcoming Events Title',
  events_past_title: 'Past Events Title',
  events_past_description: 'Past Events Description',
  events_flyers_title: 'Flyers Title',
  events_cta_title: 'CTA Title',
  events_cta_description: 'CTA Description',
  events_section_title: 'Homepage Events Section Title',
  events_section_description: 'Homepage Events Section Description',
  events_view_all_cta: 'View All Events Label',
  events_stat1_label: 'Stat 1 Label',
  events_stat2_label: 'Stat 2 Label',
  events_stat3_label: 'Stat 3 Label',
  events_stat4_label: 'Stat 4 Label',
  gallery_hero_title: 'Hero Title',
  gallery_hero_description: 'Hero Description',
  gallery_cta_title: 'CTA Title',
  gallery_cta_description: 'CTA Description',
  insights_cta_title: 'CTA Title',
  insights_cta_description: 'CTA Description',
  home_insights_eyebrow: 'Insights Eyebrow',
  home_insights_title: 'Insights Title',
  home_insights_cta: 'Insights CTA',
  home_insights_read_more: 'Read More Label',
  home_gallery_eyebrow: 'Gallery Eyebrow',
  home_gallery_title: 'Gallery Title',
  home_gallery_cta: 'Gallery CTA',
  home_help_title: 'Help Banner Title',
  home_help_description: 'Help Banner Description',
  home_help_cta: 'Help Banner CTA',
  home_help_call_label: 'Call Us Label',
  home_help_note_prefix: 'Note Prefix',
  home_help_or_call: 'Or Call Label',
  event_banner_eyebrow: 'Event Banner Eyebrow',
  event_banner_cta: 'Event Banner CTA',
  impact_eyebrow: 'Impact Eyebrow',
  impact_title: 'Impact Title',
  impact_description: 'Impact Description',
  impact_stat1_label: 'Impact Stat 1 Label',
  impact_stat2_label: 'Impact Stat 2 Label',
  impact_stat3_label: 'Impact Stat 3 Label',
  donate_eyebrow: 'Donate Eyebrow',
  donate_title: 'Donate Title',
  donate_description: 'Donate Description',
  donate_cta: 'Donate CTA Label',
  partners_eyebrow: 'Partners Eyebrow',
  partners_title: 'Partners Title',
  partners_description: 'Partners Description',
  partners_cta: 'Partners CTA',
  partners_bottom_label: 'Partners Bottom Label',
  partners_bottom_note: 'Partners Bottom Note',
  partners_view_all: 'View All Partners Label',
  spotlight_eyebrow: 'Spotlight Eyebrow',
  spotlight_title: 'Spotlight Title',
  spotlight_description: 'Spotlight Description',
  video_eyebrow: 'Video Eyebrow',
  video_title: 'Video Title',
  video_description: 'Video Description',
  footer_quick_links_title: 'Footer Quick Links Title',
  footer_support_title: 'Footer Support Title',
  footer_newsletter_title: 'Footer Newsletter Title',
};

export const DESCRIPTIONS: Record<string, string> = {
  site_name: 'Full legal name shown in the header, footer and meta tags.',
  site_short_name: 'Short name used in compact spaces like the favicon tooltip.',
  site_tagline: 'One-line tagline under the logo.',
  site_description: 'Default meta description for pages without a specific one.',
  seo_title: 'Fallback page title for search engines.',
  seo_description: 'Fallback meta description for search engines.',
  hero_headline: 'Main headline on the landing page hero.',
  hero_tagline: 'Supporting paragraph under the headline.',
  hero_slides: 'Images that rotate in the hero slider. Order = display order.',
  video_url: 'Path or URL to the “Our Story” video file.',
  footer_about: 'Short blurb in the site footer.',
  newsletter_text: 'Blurb under the newsletter signup.',
  contact_email: 'Public contact email address.',
  contact_phone: 'Phone number as displayed to visitors.',
  contact_phone_raw: 'International format used for tel: links.',
  contact_address: 'Physical office address.',
  contact_whatsapp: 'WhatsApp number in international format.',
  contact_map_query: 'Google Maps search query for the embedded map.',
  contact_office_hours: 'Weekly office hours shown on the contact page.',
  contact_faqs: 'Frequently asked questions and answers.',
  support_whatsapp: 'WhatsApp number for the floating support widget.',
  support_phone: 'Phone number for the floating support widget.',
  support_email: 'Email for the floating support widget.',
  support_crisis_text: 'Urgent-help disclaimer in the support widget.',
  social_facebook: 'Full URL to the Facebook page.',
  social_twitter: 'Full URL to the Twitter / X profile.',
  social_instagram: 'Full URL to the Instagram profile.',
  social_linkedin: 'Full URL to the LinkedIn page.',
  social_youtube: 'Full URL to the YouTube channel.',
  stat_people_supported: 'Number of people supported (shown in impact counters).',
  stat_community_events: 'Number of community events held.',
  stat_volunteers: 'Number of active volunteers.',
  stat_commitment: 'Commitment percentage shown in impact stats.',
  donation_bank_name: 'Bank name for donations.',
  donation_account_number: 'Account number for donations.',
  donation_account_name: 'Account holder name for donations.',
  donation_sort_code: 'Sort code / branch code for donations.',
  about_values: 'List of organisational values (name + description).',
  about_areas: 'List of intervention areas (title + description).',
  about_milestones: 'Timeline milestones (year + title + description).',
  help_helplines: 'Crisis and support helplines (name, number, availability).',
  help_channels: 'Alternate contact channels (label, action, colour).',
  help_warning_signs: 'Bullet list of warning signs to watch for.',
  help_self_care_steps: 'Ordered self-care steps (step, title, description).',
  services_list: 'Six service cards shown on the What We Do page.',
  features_list: 'Three feature cards shown in the homepage services section.',
  partners_list: 'Partner organisations grouped by category (legacy homepage list — manage Partners via the Partners admin page).',
  resources_page_eyebrow: 'Eyebrow label above the /resources hero title.',
  resources_page_title: 'First part of the /resources hero title.',
  resources_page_title_highlight: 'Highlighted second part of the /resources hero title.',
  resources_page_description: 'Intro paragraph on the /resources page.',
  partners_page_eyebrow: 'Eyebrow label above the /partners hero title.',
  partners_page_title: 'First part of the /partners hero title.',
  partners_page_title_highlight: 'Highlighted second part of the /partners hero title.',
  partners_page_description: 'Intro paragraph on the /partners page.',
  registration_interests: 'Interest options in the registration form.',
  org_legal_name: 'Full registered name of the organisation.',
  org_logo: 'Logo used in official documents and the admin panel.',
  org_registration_number: 'NGO / CAC registration number shown in the footer or about page.',
  org_founded_year: 'Year the organisation was founded.',
  org_website: 'Primary website URL.',
  org_motto: 'Official motto or slogan.',
  projects_categories: 'Filter categories on the projects listing.',
  gallery_categories: 'Filter categories on the gallery listing.',
  insights_trending_tags: 'Trending tag chips on the insights listing.',
  wwd_hero_image: 'Background image for the What We Do hero.',
  wwd_steps: 'How-it-works steps (step, title, description).',
  wwd_meta_title: 'Browser tab title for the What We Do page.',
  wwd_meta_description: 'Meta description for the What We Do page.',
  services_bg_image: 'Background image for the homepage services section.',
  involve_ways: 'Volunteer / Partner / Donate / Spread the Word cards.',
  involve_steps: 'Three-step “Getting Started” process.',
};

export const HINTS: Record<string, string> = {
  contact_phone: 'e.g. 0805 177 2262',
  contact_phone_raw: 'e.g. +2348051772262',
  contact_whatsapp: 'International format, e.g. +2348051772262',
  support_whatsapp: 'International format, e.g. +2348051772262',
  support_phone: 'International format, e.g. +2348051772262',
  contact_map_query: 'URL-encoded, e.g. Kubwa+Bwari+Area+Council+Abuja+Nigeria',
  social_facebook: 'https://facebook.com/…',
  social_twitter: 'https://x.com/…',
  social_instagram: 'https://instagram.com/…',
  social_linkedin: 'https://linkedin.com/…',
  social_youtube: 'https://youtube.com/…',
  video_url: '/video/file.mp4 or https://…',
  wwd_hero_image: '/images/… or https://…',
  services_bg_image: '/images/… or https://…',
  donation_account_number: 'e.g. 0123456789',
  stat_commitment: '0–100',
};

export function humanizeKey(key: string): string {
  return key
    .split('_')
    .map((w) => (w.length <= 2 && w === w.toUpperCase() ? w : w.charAt(0).toUpperCase() + w.slice(1)))
    .join(' ');
}

export function labelFor(key: string): string {
  if (LABELS[key]) return LABELS[key];
  return humanizeKey(key);
}

export function descriptionFor(key: string): string | undefined {
  return DESCRIPTIONS[key];
}

export function hintFor(key: string): string | undefined {
  return HINTS[key];
}

export function looksLikeJson(value: string): boolean {
  const t = value.trim();
  return t.startsWith('[') || t.startsWith('{');
}

export function tryParseJson(value: string): { ok: boolean; pretty?: string; error?: string } {
  try {
    const parsed = JSON.parse(value);
    return { ok: true, pretty: JSON.stringify(parsed, null, 2) };
  } catch (e: any) {
    return { ok: false, error: e.message || 'Invalid JSON' };
  }
}

export function inputTypeFor(key: string, type: string): string {
  if (type === 'NUMBER') return 'number';
  if (key === 'contact_email' || key === 'support_email') return 'email';
  if (
    key === 'contact_phone' ||
    key === 'contact_phone_raw' ||
    key === 'contact_whatsapp' ||
    key === 'support_phone' ||
    key === 'support_whatsapp'
  )
    return 'tel';
  if (
    key.endsWith('_url') ||
    key.startsWith('social_') ||
    key === 'contact_map_query' ||
    key.includes('ctaUrl') ||
    key.includes('href')
  )
    return 'url';
  return 'text';
}
